In [1]:
import pandas as pd
import numpy as np
import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

pd.options.display.float_format = '{:,.2f}'.format

data = pd.read_csv('nobel_prize_data.csv')

print(f'Shape : {data.shape}')
data.head()

Shape : (962, 16)

,year,category,prize,motivation,prize_share,laureate_type,full_name,birth_date,birth_city,birth_country,birth_country_current,sex,organization_name,organization_city,organization_country,ISO
0,1901,Chemistry,The Nobel Prize in Chemistry 1901,"""in recognition of the extraordinary services ...",1/1,Individual,Jacobus Henricus van 't Hoff,1852-08-30,Rotterdam,Netherlands,Netherlands,Male,Berlin University,Berlin,Germany,NLD
1,1901,Literature,The Nobel Prize in Literature 1901,"""in special recognition of his poetic composit...",1/1,Individual,Sully Prudhomme,1839-03-16,Paris,France,France,Male,NaN,NaN,NaN,FRA
2,1901,Medicine,The Nobel Prize in Physiology or Medicine 1901,"""for his work on serum therapy, especially its...",1/1,Individual,Emil Adolf von Behring,1854-03-15,Hansdorf (Lawice),Prussia (Poland),Poland,Male,Marburg University,Marburg,Germany,POL
3,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,Individual,Frédéric Passy,1822-05-20,Paris,France,France,Male,NaN,NaN,NaN,FRA
4,1901,Peace,The Nobel Peace Prize 1901,NaN,1/2,Individual,Jean Henry Dunant,1828-05-08,Geneva,Switzerland,Switzerland,Male,NaN,NaN,NaN,CHE

In [2]:
print(f'Duplicates? : {data.duplicated().values.any()}')
print(f'NaN values : {data.isna().values.any()}')
print(data.isna().sum().to_string())

Duplicates? : False
NaN values : True
year                       0
category                   0
prize                      0
motivation                88
prize_share                0
laureate_type              0
full_name                  0
birth_date                28
birth_city                31
birth_country             28
birth_country_current     28
sex                       28
organization_name        255
organization_city        255
organization_country     254
ISO                       28

In [3]:
col_subset = ['year', 'category', 'laureate_type', 'birth_date', 'full_name', 'organization_name']
data.loc[data.birth_date.isna()][col_subset]

,year,category,laureate_type,birth_date,full_name,organization_name
24,1904,Peace,Organization,NaN,Institut de droit international (Institute of ...,NaN
60,1910,Peace,Organization,NaN,Bureau international permanent de la Paix (Per...,NaN
89,1917,Peace,Organization,NaN,Comité international de la Croix Rouge (Intern...,NaN
200,1938,Peace,Organization,NaN,Office international Nansen pour les Réfugiés ...,NaN
215,1944,Peace,Organization,NaN,Comité international de la Croix Rouge (Intern...,NaN
237,1947,Peace,Organization,NaN,American Friends Service Committee (The Quakers),NaN
238,1947,Peace,Organization,NaN,Friends Service Council (The Quakers),NaN
283,1954,Peace,Organization,NaN,Office of the United Nations High Commissioner...,NaN
348,1963,Peace,Organization,NaN,Comité international de la Croix Rouge (Intern...,NaN
349,1963,Peace,Organization,NaN,Ligue des Sociétés de la Croix-Rouge (League o...,NaN
366,1965,Peace,Organization,NaN,United Nations Children's Fund (UNICEF),NaN
399,1969,Peace,Organization,NaN,International Labour Organization (I.L.O.),NaN
479,1977,Peace,Organization,NaN,Amnesty International,NaN
523,1981,Peace,Organization,NaN,Office of the United Nations High Commissioner...,NaN
558,1985,Peace,Organization,NaN,International Physicians for the Prevention of...,NaN
588,1988,Peace,Organization,NaN,United Nations Peacekeeping Forces,NaN
659,1995,Peace,Organization,NaN,Pugwash Conferences on Science and World Affairs,NaN
682,1997,Peace,Organization,NaN,International Campaign to Ban Landmines (ICBL),NaN
703,1999,Peace,Organization,NaN,Médecins Sans Frontières,NaN
730,2001,Peace,Organization,NaN,United Nations (U.N.),NaN
778,2005,Peace,Organization,NaN,International Atomic Energy Agency (IAEA),NaN
788,2006,Peace,Organization,NaN,Grameen Bank,NaN
801,2007,Peace,Organization,NaN,Intergovernmental Panel on Climate Change (IPCC),NaN
860,2012,Peace,Organization,NaN,European Union (EU),NaN
873,2013,Peace,Organization,NaN,Organisation for the Prohibition of Chemical W...,NaN
897,2015,Peace,Organization,NaN,National Dialogue Quartet,NaN
919,2017,Peace,Organization,NaN,International Campaign to Abolish Nuclear Weap...,NaN
958,2020,Peace,Organization,NaN,World Food Programme (WFP),NaN

In [4]:
data.birth_date = pd.to_datetime(data.birth_date)
seperated_values = data.prize_share.str.split('/', expand=True)

numerator = pd.to_numeric(seperated_values[0])
denominator = pd.to_numeric(seperated_values[1])

data['share_pct'] = numerator / denominator

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 962 entries, 0 to 961
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   year                   962 non-null    int64
 1   category               962 non-null    object
 2   prize                  962 non-null    object
 3   motivation             874 non-null    object
 4   prize_share            962 non-null    object
 5   laureate_type          962 non-null    object
 6   full_name              962 non-null    object
 7   birth_date             934 non-null    datetime64[ns]
 8   birth_city             931 non-null    object
 9   birth_country          934 non-null    object
 10  birth_country_current  934 non-null    object
 11  sex                    934 non-null    object
 12  organization_name      707 non-null    object
 13  organization_city      707 non-null    object
 14  organization_country   708 non-null    object
 15  ISO                    934 non-null    object
 16  share_pct              962 non-null    float64
dtypes: datetime64[ns](1), float64(1), int64(1), object(14)
memory usage: 127.9+ KB