In [6]:
import pandas as pd 
df = pd.read_csv('QueryResults.csv', names=['DATE', 'TAG', 'POSTS'], header=0)

df.head()

                  DATE         TAG  POSTS
0  2008-07-01 00:00:00          c#      3
1  2008-08-01 00:00:00    assembly      8
2  2008-08-01 00:00:00  javascript    162
3  2008-08-01 00:00:00           c     85
4  2008-08-01 00:00:00      python    124

In [7]:
df.tail()

                     DATE    TAG  POSTS
1986  2020-07-01 00:00:00      r   5694
1987  2020-07-01 00:00:00     go    743
1988  2020-07-01 00:00:00   ruby    775
1989  2020-07-01 00:00:00   perl    182
1990  2020-07-01 00:00:00  swift   3607

In [8]:
df.shape

(1991, 3)

In [9]:
df.columns

Index(['DATE', 'TAG', 'POSTS'], dtype='object')

In [10]:
df.count()

DATE     1991
TAG      1991
POSTS    1991
dtype: int64