In [1]:
import pandas as pd
import plotly.express as px

df_apps = pd.read_csv('apps.csv')

In [2]:
df_apps.shape

(10841, 12)

In [3]:
df_apps.columns

Index(['App', 'Category', 'Rating', 'Reviews', 'Size_MBs', 'Installs', 'Type',
       'Price', 'Content_Rating', 'Genres', 'Last_Updated', 'Android_Ver'],
      dtype='object')

In [4]:
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres,Last_Updated,Android_Ver
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7,0,Paid,$13.99,Teen,Social,"July 28, 2017",4.1 and up
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.0,0,Paid,$2.99,Everyone,Education,"April 15, 2016",3.0 and up
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5,0,Paid,$1.49,Everyone,Personalization,"July 11, 2018",4.2 and up
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.0,0,NaN,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device
4,CX Network,BUSINESS,NaN,0,10.0,0,Free,0,Everyone,Business,"August 6, 2018",4.1 and up

In [5]:
df_apps.drop(['Last_Updated', 'Android_Ver'], axis=1, inplace=True)
df_apps.head()

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.0,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.0,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.0,0,Free,0,Everyone,Business

In [6]:
nan_rows = df_apps[df_apps.Rating.isna()]
print(nan_rows.shape)

nan_rows.head()

(1474, 10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
0,Ak Parti Yardım Toplama,SOCIAL,NaN,0,8.7,0,Paid,$13.99,Teen,Social
1,Ain Arabic Kids Alif Ba ta,FAMILY,NaN,0,33.0,0,Paid,$2.99,Everyone,Education
2,Popsicle Launcher for Android P 9.0 launcher,PERSONALIZATION,NaN,0,5.5,0,Paid,$1.49,Everyone,Personalization
3,Command & Conquer: Rivals,FAMILY,NaN,0,19.0,0,NaN,0,Everyone 10+,Strategy
4,CX Network,BUSINESS,NaN,0,10.0,0,Free,0,Everyone,Business

In [7]:
df_apps_clean = df_apps.dropna()
df_apps_clean.shape

(9367, 10)

In [8]:
duplicated_rows = df_apps_clean[df_apps_clean.duplicated()]
print(duplicated_rows.shape)

duplicated_rows.head()

(476, 10)

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
946,420 BZ Budeze Delivery,MEDICAL,5.0,2,11.0,100,Free,0,Mature 17+,Medical
1133,MouseMingle,DATING,2.7,3,3.9,100,Free,0,Mature 17+,Dating
1196,"Cardiac diagnosis (heart rate, arrhythmia)",MEDICAL,4.4,8,6.5,100,Paid,$12.99,Everyone,Medical
1231,Sway Medical,MEDICAL,5.0,3,22.0,100,Free,0,Everyone,Medical
1247,Chat Kids - Chat Room For Kids,DATING,4.7,6,4.9,100,Free,0,Mature 17+,Dating

In [9]:
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social
10808,Instagram,SOCIAL,4.5,66577446,5.3,"1,000,000,000",Free,0,Teen,Social
10809,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social
10810,Instagram,SOCIAL,4.5,66509917,5.3,"1,000,000,000",Free,0,Teen,Social

In [10]:
df_apps_clean = df_apps_clean.drop_duplicates(subset=['App', 'Type', 'Price'])
df_apps_clean[df_apps_clean.App == 'Instagram']

,App,Category,Rating,Reviews,Size_MBs,Installs,Type,Price,Content_Rating,Genres
10806,Instagram,SOCIAL,4.5,66577313,5.3,"1,000,000,000",Free,0,Teen,Social

In [11]:
df_apps_clean.shape

(8199, 10)

In [12]:
ratings = df_apps_clean.Content_Rating.value_counts()

In [13]:
ratings

Content_Rating
Everyone           6621
Teen                912
Mature 17+          357
Everyone 10+        305
Adults only 18+       3
Unrated               1
Name: count, dtype: int64

In [14]:
fig = px.pie(labels=ratings.index, values=ratings.values)
fig.show()

In [15]:
fig = px.pie(labels=ratings.index, values=ratings.values, title='Content Rating', names=ratings.index)

fig.update_traces(textposition='outside', textinfo='percent+label')

fig.show()

In [18]:
fig = px.pie(labels=ratings.index, values=ratings.values, title='Content Rating', names=ratings.index, hole=0.6)

fig.update_traces(textposition='inside', textinfo='percent', textfont_size=15)

fig.show()

In [19]:
df_apps_clean.Installs.describe()

count          8199
unique           19
top       1,000,000
freq           1417
Name: Installs, dtype: object

In [21]:
df_apps_clean.Installs = df_apps_clean.Installs.astype(str).str.replace(',',"")
df_apps_clean.Installs = pd.to_numeric(df_apps_clean.Installs)

df_apps_clean[['App', 'Installs']].groupby('Installs').count()

             App
Installs
1              3
5              9
10            69
50            56
100          303
500          199
1000         698
5000         425
10000        988
50000        457
100000      1096
500000       504
1000000     1417
5000000      607
10000000     933
50000000     202
100000000    189
500000000     24
1000000000    20

In [22]:
df_apps_clean.Category.nunique()

33

In [25]:
top10_category = df_apps_clean.Category.value_counts()[:10]

In [26]:
bar = px.bar(x = top10_category.index, y = top10_category.values)
bar.show()

In [27]:
category_installs = df_apps_clean.groupby('Category').agg({'Installs': pd.Series.sum})
category_installs.sort_values('Installs', ascending=True, inplace=True)

In [28]:
h_bar = px.bar(x = category_installs.Installs, y = category_installs.index, orientation='h', title='Category Popularity')

h_bar.update_layout(xaxis_title='Total Downloads', yaxis_title='Category')

h_bar.show()

In [29]:
scat_num = df_apps_clean.groupby('Category').agg({'App': pd.Series.count})

scat_merged_df = pd.merge(scat_num, category_installs, on='Category', how='inner')
print(f'DataFrame Dimensions : {scat_merged_df.shape}')

scat_merged_df.sort_values('Installs', ascending=False)

DataFrame Dimensions : (33, 2)

                      App     Installs
Category
GAME                  910  13858762717
COMMUNICATION         257  11039241530
TOOLS                 719   8099724500
PRODUCTIVITY          301   5788070180
SOCIAL                203   5487841475
PHOTOGRAPHY           263   4649143130
FAMILY               1610   4437579590
VIDEO_PLAYERS         148   3916897200
TRAVEL_AND_LOCAL      187   2894859300
NEWS_AND_MAGAZINES    204   2369110650
ENTERTAINMENT         102   2113660000
BOOKS_AND_REFERENCE   169   1665791655
PERSONALIZATION       298   1532352930
SHOPPING              180   1400331540
HEALTH_AND_FITNESS    243   1134006220
SPORTS                260   1096431465
BUSINESS              262    692018120
LIFESTYLE             302    503742120
MAPS_AND_NAVIGATION   118    503267560
FINANCE               302    455312400
WEATHER                72    361096500
EDUCATION             118    352852000
FOOD_AND_DRINK         94    211677750
DATING                134    140912410
ART_AND_DESIGN         61    114233100
HOUSE_AND_HOME         62     97082000
AUTO_AND_VEHICLES      73     53129800
LIBRARIES_AND_DEMO     64     52083000
COMICS                 54     44931100
MEDICAL               292     39162676
PARENTING              50     31116110
BEAUTY                 42     26916200
EVENTS                 45     15949410

In [30]:
scatter = px.scatter(scat_merged_df, x = 'App', y = 'Installs', title = 'Category Concentration', size = 'App', hover_name = scat_merged_df.index, color = 'Installs')

scatter.update_layout(xaxis_title = 'Total Apps (Lower = More Concentrated)', yaxis_title = 'Installs', yaxis = dict(type = 'log'))

scatter.show()

In [31]:
len(df_apps_clean.Genres.unique())

114

In [32]:
df_apps_clean.Genres.value_counts().sort_values(ascending=True)[:5]

Genres
Adventure;Education            1
Lifestyle;Pretend Play         1
Strategy;Education             1
Communication;Creativity       1
Music & Audio;Music & Video    1
Name: count, dtype: int64

In [34]:
stack = df_apps_clean.Genres.str.split(';', expand=True).stack()
print(f'Single column shape : {stack.shape}')

num_genres = stack.value_counts()
print(f'Total genres : {len(num_genres)}')

Single column shape : (8579,)
Total genres : 53

In [35]:
bar = px.bar(x = num_genres.index[:15], y = num_genres.values[:15], title = 'Top Genres', hover_name = num_genres.index[:15], color = num_genres.values[:15], color_continuous_scale='Agsunset')

bar.update_layout(xaxis_title = 'Genre', yaxis_title = 'Total Apps', coloraxis_showscale = False)

bar.show()

In [36]:
df_apps_clean.Type.value_counts()

Type
Free    7595
Paid     604
Name: count, dtype: int64

In [37]:
df_free_vs_paid = df_apps_clean.groupby(['Category', 'Type'], as_index=False).agg({'App': pd.Series.count})
df_free_vs_paid.head()

            Category  Type  App
0     ART_AND_DESIGN  Free   58
1     ART_AND_DESIGN  Paid    3
2  AUTO_AND_VEHICLES  Free   72
3  AUTO_AND_VEHICLES  Paid    1
4             BEAUTY  Free   42

In [38]:
g_bar = px.bar(df_free_vs_paid, x = 'Category', y = 'App', title = 'Free v/s Paid Apps by Category', color = 'Type', barmode = 'group')

g_bar.update_layout(xaxis_title = 'Category', yaxis_title = 'Total Apps', xaxis = {'categoryorder': 'total descending'}, yaxis = dict(type='log'))

g_bar.show()

In [40]:
box = px.box(df_apps_clean, x = 'Type', y = 'Installs', color = 'Type', notched = True, points = 'all', title = 'Total downloads paid apps give up are?')

box.update_layout(yaxis = dict(type='log'))

box.show()

In [43]:
df_apps_clean['Installs'] = df_apps_clean['Installs'].astype(str).str.replace(',', '').astype(int)
df_apps_clean['Price'] = df_apps_clean['Price'].astype(str).str.replace('$', '').astype(float)

df_apps_clean['Revenue_Estimate'] = df_apps_clean['Installs'] * df_apps_clean['Price']

In [44]:
df_apps_paid = df_apps_clean[df_apps_clean.Type == 'Paid']
box = px.box(df_apps_paid,
            y='Revenue_Estimate',
            x='Category',
            title='How much can paid apps earn?',
            )

box.update_layout(yaxis=dict(type='log'),
                xaxis_title='Category',
                yaxis_title='Paid App Ballpark Revenue',
                xaxis_tickangle=30,
                xaxis={'categoryorder':'min ascending'})

box.show()

In [45]:
box = px.box(df_apps_paid,
            y='Price',
            x='Category',
            title='Price per Category',
            )

box.update_layout(yaxis=dict(type='log'),
                xaxis_title='Category',
                yaxis_title='Paid App Price',
                xaxis_tickangle=30,
                xaxis={'categoryorder':'max descending'})

box.show()