In [18]:
import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')

df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.isna()

In [ ]:
df.tail()

In [ ]:
clear_df = df.dropna()
clear_df.tail()

In [ ]:
clear_df['Starting Median Salary'].max()

np.float64(74300.0)

In [26]:
clear_df['Starting Median Salary'].idxmax()

np.int64(43)

In [27]:
clear_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [28]:
clear_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [29]:
print(clear_df['Mid-Career Median Salary'].max())
print(f'Max Mid-Career Salary Index : {clear_df['Mid-Career Median Salary'].idxmax()}')
clear_df['Undergraduate Major'][8]

107000.0
Max Mid-Career Salary Index : 8

'Chemical Engineering'

In [31]:
print(clear_df['Starting Median Salary'].min())
clear_df['Undergraduate Major'].loc[clear_df['Starting Median Salary'].idxmin()]

34000.0

'Spanish'

In [32]:
clear_df.loc[clear_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [33]:
spread_col = clear_df['Mid-Career 90th Percentile Salary'].subtract(clear_df['Mid-Career 10th Percentile Salary'])
clear_df.insert(1, 'Spread', spread_col)
clear_df.head()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,109800.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,96700.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,113700.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,104200.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,85400.0,41600.0,76800.0,50600.0,136000.0,Business

In [34]:
low_risk = clear_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [35]:
highest_potential = clear_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [36]:
highest_spread = clear_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0